spring:
  application:
    name: springboot-2018
  datasource:
    url: 'jdbc:mysql://localhost:3306/webtest?
          createDatabaseIfNotExist=true
          &serverTimezone=Asia/Shanghai'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
my:
  secretkey: R28K42ZEJ8LWRHU5
  salt: 636eac2534bcfcb0
logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
